export default {
    GET_HACK_NEWS: "GET_HACK_NEWS",
    FETCH_NEWS:"FETCH_NEWS",
    FETCH_NEWS_SUCCESS:"FETCH_NEWS_SUCCESS",
    FETCH_NEWS_FAILURE:"FETCH_NEWS_FAILURE",

    FETCH_NEWS_ID_LIST:"FETCH_NEWS_ID_LIST",
    FETCH_NEWS_ID_LIST_SUCCESS:"FETCH_NEWS_ID_LIST_SUCCESS",
    FETCH_NEWS_ID_LIST_FAILURE:"FETCH_NEWS_ID_LIST_FAILURE",

    SET_STARRED:"SET_STARRED",
}